### ISSUE TITLE
No such file or directory: '../from_hixon/mix_data_new_normal_label_smoothing/model_weights.pt'

### ISSUE THREAD

**Issue by joelonsql** [omron-sinicx/transformer4sr#2]
Where can I download the needed `model_weights.pt` file from?

```
joel@Joels-MacBook-Pro transformer4sr % python3 evaluate_model.py
Traceback (most recent call last):
  File "/Users/joel/src/transformer4sr/evaluate_model.py", line 25, in <module>
    hixon_state_dict = torch.load(path_model_weights, map_location=torch.device('cpu'))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../from_hixon/mix_data_new_normal_label_smoothing/model_weights.pt'
```

**Comment by DeltaFloflo** [comment]
Hey, thanks for reaching out. Sorry for the hardcoded path, I have updated it.
The weights are in `best_model_weights/`, and default is `mix_label_smoothing/` (our best model).
